"""empty message

Revision ID: 5bdf3e0df94e
Revises: 9fe11ba9dc58
Create Date: 2021-10-26 22:40:36.435597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bdf3e0df94e'
down_revision = '9fe11ba9dc58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drinks', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'drinks', 'users', ['user_id'], ['id'])
    op.add_column('ingredients', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('ingredients_drink_id_fkey', 'ingredients', type_='foreignkey')
    op.create_foreign_key(None, 'ingredients', 'users', ['user_id'], ['id'])
    op.drop_column('ingredients', 'drink_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('drink_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ingredients', type_='foreignkey')
    op.create_foreign_key('ingredients_drink_id_fkey', 'ingredients', 'drinks', ['drink_id'], ['id'])
    op.drop_column('ingredients', 'user_id')
    op.drop_constraint(None, 'drinks', type_='foreignkey')
    op.drop_column('drinks', 'user_id')
    # ### end Alembic commands ###
