# This is a basic workflow to help you get started with Actions

name: Python Application

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Login to Heroku Container Registry
        run: heroku container:login

      # Runs a set of commands using the runners shell
      - name: Build and push
        run: heroku container:push -a cocktail-party-app web
      - name: Release
        run: heroku container:release -a cocktail-party-app web
